### ISSUE TITLE
[Solution] 500 Internal Server Error due to tensorboard update

### ISSUE THREAD

**Issue by NanoCode012** [chaoleili/jupyterlab_tensorboard#25]
Some info redacted.
```
Uncaught exception POST /api/tensorboard?XXXX
    HTTPServerRequest(protocol='http', host='', method='POST', uri='/api/tensorboard?XXXX', version='HTTP/1.1', remote_ip='')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1701, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 3178, in wrapper
        return method(self, *args, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/jupyter_tensorboard/api_handlers.py", line 40, in post
        .new_instance(data["logdir"], reload_interval=reload_interval)
      File "/opt/conda/lib/python3.6/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 221, in new_instance
        purge_orphaned_data=purge_orphaned_data)
      File "/opt/conda/lib/python3.6/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 44, in create_tb_app
        return application.standard_tensorboard_wsgi(
    AttributeError: module 'tensorboard.backend.application' has no attribute 'standard_tensorboard_wsgi'
```

After some digging around, latest version of tensorboard does not have that attribute in error above: https://github.com/tensorflow/tensorboard/blob/master/tensorboard/backend/application.py

The latest one I saw was `tensorboard==2.2`

https://github.com/tensorflow/tensorboard/blob/2.2/tensorboard/backend/application.py .

Simple solution would be to tell users to `pip install tensorboard==2.2`.

**Comment by RW21** [comment]
Its due to this PR https://github.com/tensorflow/tensorboard/pull/3643

**Comment by qrtt1** [comment]
We fixed the serverside extension in the main branch https://github.com/InfuseAI/jupyter_tensorboard

However, the frontend requests to the incorrect path:
![image](https://user-images.githubusercontent.com/193223/100566068-031a3d80-3300-11eb-903b-21b7663f6447.png)

**Comment by rragundez** [comment]
any update on this one? is it solved yet?

**Comment by drykovanov** [comment]
I had to patch jupyter_tensorboard to run with tf 2.3.x:
https://github.com/drykovanov/jupyter_tensorboard/tree/tf230

**Comment by rragundez** [comment]
so how do I install it @drykovanov ?

**Comment by rragundez** [comment]
ping @drykovanov

**Comment by drykovanov** [comment]
> so how do I install it @drykovanov ?

Hi @rragundez , you can just checkout the patched branch and `pip install .` in the _jupyter_tensorboard_ directory.

**Comment by RW21** [comment]
Are the new patches going to be merged into this brach?

**Comment by mgomesborges** [comment]
For me it is working correctly using the following configuration (with TensorFlow 2.4.1 installed):

```bash
# Keep compatibility with jupyterlab_tensorboard
# jupyterlab==2.2.9 < 3.x
pip install jupyterlab==2.2.9 jupyterlab_widgets ipywidgets

# Tensorboard
pip install tensorboard==2.4.1 tensorboard_plugin_profile jupyter-tensorboard==0.2.0
```

```bash
jupyter labextension install jupyterlab_tensorboard --no-build

jupyter lab clean
jupyter lab build

jupyter labextension list
``
